import type { ColorPreset, TemplateData, Tier } from './types'

export const COLOR_PRESETS: ColorPreset[] = [
  { id: 'red', name: 'Ruby Red', bg: '#ef4444', text: '#ffffff', border: '#dc2626' },
  { id: 'rose', name: 'Rose Pink', bg: '#f43f5e', text: '#ffffff', border: '#e11d48' },
  { id: 'orange', name: 'Amber Orange', bg: '#f97316', text: '#ffffff', border: '#ea580c' },
  { id: 'amber', name: 'Warm Amber', bg: '#f59e0b', text: '#000000', border: '#d97706' },
  { id: 'yellow', name: 'Bright Gold', bg: '#eab308', text: '#000000', border: '#ca8a04' },
  { id: 'lime', name: 'Neon Lime', bg: '#84cc16', text: '#000000', border: '#65a30d' },
  { id: 'green', name: 'Emerald Green', bg: '#10b981', text: '#ffffff', border: '#059669' },
  { id: 'teal', name: 'Cyan Teal', bg: '#14b8a6', text: '#ffffff', border: '#0d9488' },
  { id: 'cyan', name: 'Sky Cyan', bg: '#06b6d4', text: '#ffffff', border: '#0891b2' },
  { id: 'blue', name: 'Electric Blue', bg: '#3b82f6', text: '#ffffff', border: '#2563eb' },
  { id: 'indigo', name: 'Deep Indigo', bg: '#6366f1', text: '#ffffff', border: '#4f46e5' },
  { id: 'violet', name: 'Royal Violet', bg: '#8b5cf6', text: '#ffffff', border: '#7c3aed' },
  { id: 'purple', name: 'Neon Purple', bg: '#a855f7', text: '#ffffff', border: '#9333ea' },
  { id: 'fuchsia', name: 'Hot Fuchsia', bg: '#d946ef', text: '#ffffff', border: '#c026d3' },
  { id: 'slate', name: 'Steel Slate', bg: '#64748b', text: '#ffffff', border: '#475569' },
  { id: 'zinc', name: 'Dark Zinc', bg: '#3f3f46', text: '#ffffff', border: '#27272a' },
]

export const DEFAULT_TIERS: Tier[] = [
  { id: 'tier-s', title: 'S', color: '#ef4444', textColor: '#ffffff' },
  { id: 'tier-a', title: 'A', color: '#f97316', textColor: '#ffffff' },
  { id: 'tier-b', title: 'B', color: '#f59e0b', textColor: '#000000' },
  { id: 'tier-c', title: 'C', color: '#10b981', textColor: '#ffffff' },
  { id: 'tier-d', title: 'D', color: '#06b6d4', textColor: '#ffffff' },
  { id: 'tier-f', title: 'F', color: '#8b5cf6', textColor: '#ffffff' },
]

export const TEMPLATES: TemplateData[] = [
  {
    id: 'games',
    name: 'Top Video Games',
    description: 'Rank all-time greatest video games across history and genres',
    icon: '🎮',
    category: 'Gaming',
    title: 'All-Time Greatest Video Games Tier List',
    subtitle: 'Ranked live based on gameplay, story, innovation, and impact',
    author: 'Live Streamer',
    tiers: [
      { id: 'tier-s', title: 'GOAT (Masterpiece)', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'Must Play (Elite)', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'Great Fun', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'Decent / Average', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'Overrated / Meh', color: '#06b6d4', textColor: '#ffffff' },
      { id: 'tier-f', title: 'Not For Me', color: '#8b5cf6', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'g-1',
        title: 'Elden Ring',
        imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80',
        category: 'Action RPG',
        subtitle: 'FromSoftware',
      },
      {
        id: 'g-2',
        title: 'Zelda: Tears of the Kingdom',
        imageUrl: 'https://images.unsplash.com/photo-1612287233213-90979bf3cb45?auto=format&fit=crop&w=400&q=80',
        category: 'Adventure',
        subtitle: 'Nintendo',
      },
      {
        id: 'g-3',
        title: "Baldur's Gate 3",
        imageUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=400&q=80',
        category: 'CRPG',
        subtitle: 'Larian Studios',
      },
      {
        id: 'g-4',
        title: 'Grand Theft Auto V',
        imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&q=80',
        category: 'Open World',
        subtitle: 'Rockstar Games',
      },
      {
        id: 'g-5',
        title: 'The Witcher 3: Wild Hunt',
        imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=400&q=80',
        category: 'RPG',
        subtitle: 'CD Projekt RED',
      },
      {
        id: 'g-6',
        title: 'Cyberpunk 2077',
        imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=400&q=80',
        category: 'Sci-Fi RPG',
        subtitle: 'CD Projekt RED',
      },
      {
        id: 'g-7',
        title: 'Minecraft',
        imageUrl: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?auto=format&fit=crop&w=400&q=80',
        category: 'Sandbox',
        subtitle: 'Mojang',
      },
      {
        id: 'g-8',
        title: 'Red Dead Redemption 2',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
        category: 'Action Adventure',
        subtitle: 'Rockstar Games',
      },
      {
        id: 'g-9',
        title: 'God of War Ragnarök',
        imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=400&q=80',
        category: 'Action',
        subtitle: 'Santa Monica',
      },
      {
        id: 'g-10',
        title: 'Hollow Knight',
        imageUrl: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=400&q=80',
        category: 'Metroidvania',
        subtitle: 'Team Cherry',
      },
      {
        id: 'g-11',
        title: 'Dark Souls III',
        imageUrl: 'https://images.unsplash.com/photo-1560253023-3ec5d502959f?auto=format&fit=crop&w=400&q=80',
        category: 'Souls-like',
        subtitle: 'FromSoftware',
      },
      {
        id: 'g-12',
        title: 'Super Mario Odyssey',
        imageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=400&q=80',
        category: 'Platformer',
        subtitle: 'Nintendo',
      },
      {
        id: 'g-13',
        title: 'Portal 2',
        imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80',
        category: 'Puzzle',
        subtitle: 'Valve',
      },
      {
        id: 'g-14',
        title: 'Skyrim',
        imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80',
        category: 'Fantasy RPG',
        subtitle: 'Bethesda',
      },
    ],
    containers: {
      'tier-s': ['g-1', 'g-4'],
      'tier-a': ['g-2', 'g-3'],
      'tier-b': ['g-5'],
      'tier-c': [],
      'tier-d': [],
      'tier-f': [],
      POOL: ['g-6', 'g-7', 'g-8', 'g-9', 'g-10', 'g-11', 'g-12', 'g-13', 'g-14'],
    },
  },
  {
    id: 'football',
    name: 'Football / Soccer Legends',
    description: 'Rank iconic football players of all time',
    icon: '⚽',
    category: 'Sports',
    title: 'Football GOATs Tier List',
    subtitle: 'Ranked on skill, trophies, longevity, and historic moments',
    author: 'Live Streamer',
    tiers: [
      { id: 'tier-s', title: 'The GOATs', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'All-Time Legends', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'World Class Elite', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'Iconic Stars', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'Great Players', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'fb-1',
        title: 'Lionel Messi',
        imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=400&q=80',
        category: 'Forward',
        subtitle: '8x Ballon d’Or',
      },
      {
        id: 'fb-2',
        title: 'Cristiano Ronaldo',
        imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=400&q=80',
        category: 'Forward',
        subtitle: '5x Ballon d’Or',
      },
      {
        id: 'fb-3',
        title: 'Pelé',
        imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=400&q=80',
        category: 'Forward',
        subtitle: '3x World Cup Champion',
      },
      {
        id: 'fb-4',
        title: 'Diego Maradona',
        imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=400&q=80',
        category: 'Attacking Mid',
        subtitle: '1986 World Cup Champion',
      },
      {
        id: 'fb-5',
        title: 'Zinedine Zidane',
        imageUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=400&q=80',
        category: 'Midfielder',
        subtitle: 'Ballon d’Or & World Cup',
      },
      {
        id: 'fb-6',
        title: 'Ronaldinho',
        imageUrl: 'https://images.unsplash.com/photo-1543351611-58f69d7c1781?auto=format&fit=crop&w=400&q=80',
        category: 'Winger / Playmaker',
        subtitle: 'Joga Bonito Icon',
      },
      {
        id: 'fb-7',
        title: 'Kylian Mbappé',
        imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=400&q=80',
        category: 'Forward',
        subtitle: 'World Cup Winner',
      },
      {
        id: 'fb-8',
        title: 'Erling Haaland',
        imageUrl: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?auto=format&fit=crop&w=400&q=80',
        category: 'Striker',
        subtitle: 'Treble Winner',
      },
      {
        id: 'fb-9',
        title: 'Luka Modrić',
        imageUrl: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&w=400&q=80',
        category: 'Midfielder',
        subtitle: 'Ballon d’Or & 6x UCL',
      },
      {
        id: 'fb-10',
        title: 'Andres Iniesta',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=400&q=80',
        category: 'Midfielder',
        subtitle: 'World Cup Final Winner',
      },
      {
        id: 'fb-11',
        title: 'Ronaldo Nazário (R9)',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=400&q=80',
        category: 'Striker',
        subtitle: 'El Fenomeno',
      },
      {
        id: 'fb-12',
        title: 'Thierry Henry',
        imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=400&q=80',
        category: 'Forward',
        subtitle: 'Invincible & Premier League Legend',
      },
    ],
    containers: {
      'tier-s': ['fb-1', 'fb-2'],
      'tier-a': ['fb-3', 'fb-4'],
      'tier-b': ['fb-5', 'fb-6'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['fb-7', 'fb-8', 'fb-9', 'fb-10', 'fb-11', 'fb-12'],
    },
  },
  {
    id: 'tech',
    name: 'Tech & Programming',
    description: 'Rank programming languages, frameworks, and developer tools',
    icon: '💻',
    category: 'Development',
    title: 'Developer Tech Stack Tier List',
    subtitle: 'Ranked by developer experience, performance, ecosystem, and joy',
    author: 'Tech Creator',
    tiers: [
      { id: 'tier-s', title: 'S - God Tier / Daily Driver', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - S Tier Potential / Love It', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Solid & Reliable', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Fine for Legacy', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Painful / Avoid', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 't-1',
        title: 'TypeScript',
        imageUrl: 'https://images.unsplash.com/photo-1516116211227-bbc154ba4b90?auto=format&fit=crop&w=400&q=80',
        category: 'Language',
        subtitle: 'Typed JavaScript',
      },
      {
        id: 't-2',
        title: 'Rust',
        imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=400&q=80',
        category: 'Systems',
        subtitle: 'Blazing Fast & Safe',
      },
      {
        id: 't-3',
        title: 'Python',
        imageUrl: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=400&q=80',
        category: 'AI / Scripting',
        subtitle: 'AI & Data Favorite',
      },
      {
        id: 't-4',
        title: 'Go (Golang)',
        imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=400&q=80',
        category: 'Backend',
        subtitle: 'Simple Concurrency',
      },
      {
        id: 't-5',
        title: 'React',
        imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=400&q=80',
        category: 'UI Library',
        subtitle: 'Component King',
      },
      {
        id: 't-6',
        title: 'Next.js',
        imageUrl: 'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?auto=format&fit=crop&w=400&q=80',
        category: 'Framework',
        subtitle: 'Full-Stack React',
      },
      {
        id: 't-7',
        title: 'PostgreSQL',
        imageUrl: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=400&q=80',
        category: 'Database',
        subtitle: 'The Gold Standard DB',
      },
      {
        id: 't-8',
        title: 'Docker',
        imageUrl: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?auto=format&fit=crop&w=400&q=80',
        category: 'DevOps',
        subtitle: 'Containers Everywhere',
      },
      {
        id: 't-9',
        title: 'Tailwind CSS',
        imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=400&q=80',
        category: 'Styling',
        subtitle: 'Utility-first CSS',
      },
      {
        id: 't-10',
        title: 'Redis',
        imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=400&q=80',
        category: 'Cache',
        subtitle: 'In-Memory Speed',
      },
      {
        id: 't-11',
        title: 'C++',
        imageUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=400&q=80',
        category: 'Language',
        subtitle: 'Game Engine Beast',
      },
      {
        id: 't-12',
        title: 'GraphQL',
        imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=400&q=80',
        category: 'API',
        subtitle: 'Declarative Queries',
      },
    ],
    containers: {
      'tier-s': ['t-1', 't-5'],
      'tier-a': ['t-2', 't-7'],
      'tier-b': ['t-3', 't-8'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['t-4', 't-6', 't-9', 't-10', 't-11', 't-12'],
    },
  },
  {
    id: 'movies',
    name: 'Iconic Movies',
    description: 'Rank cinema masterpieces and blockbusters',
    icon: '🎬',
    category: 'Entertainment',
    title: 'Greatest Movies of All Time Tier List',
    subtitle: 'Ranked by storytelling, cinematography, acting, and replay value',
    author: 'Film Buff',
    tiers: [
      { id: 'tier-s', title: 'S - Cinema Perfection', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Absolute Classic', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Great Film', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Good Weekend Watch', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Disappointing', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'm-1',
        title: 'The Dark Knight',
        imageUrl: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=400&q=80',
        category: 'Action / Superhero',
        subtitle: 'Christopher Nolan (2008)',
      },
      {
        id: 'm-2',
        title: 'Interstellar',
        imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80',
        category: 'Sci-Fi',
        subtitle: 'Christopher Nolan (2014)',
      },
      {
        id: 'm-3',
        title: 'Inception',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
        category: 'Sci-Fi / Thriller',
        subtitle: 'Christopher Nolan (2010)',
      },
      {
        id: 'm-4',
        title: 'The Godfather',
        imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=400&q=80',
        category: 'Crime Drama',
        subtitle: 'Francis Ford Coppola (1972)',
      },
      {
        id: 'm-5',
        title: 'Pulp Fiction',
        imageUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=400&q=80',
        category: 'Neo-Noir',
        subtitle: 'Quentin Tarantino (1994)',
      },
      {
        id: 'm-6',
        title: 'The Matrix',
        imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=400&q=80',
        category: 'Sci-Fi Action',
        subtitle: 'Wachowskis (1999)',
      },
      {
        id: 'm-7',
        title: 'Spirited Away',
        imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80',
        category: 'Animation',
        subtitle: 'Hayao Miyazaki (2001)',
      },
      {
        id: 'm-8',
        title: 'Oppenheimer',
        imageUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=400&q=80',
        category: 'Biographical',
        subtitle: 'Christopher Nolan (2023)',
      },
      {
        id: 'm-9',
        title: 'Parasite',
        imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=400&q=80',
        category: 'Thriller / Satire',
        subtitle: 'Bong Joon-ho (2019)',
      },
      {
        id: 'm-10',
        title: 'Gladiator',
        imageUrl: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?auto=format&fit=crop&w=400&q=80',
        category: 'Historical Epic',
        subtitle: 'Ridley Scott (2000)',
      },
    ],
    containers: {
      'tier-s': ['m-1', 'm-2'],
      'tier-a': ['m-4', 'm-6'],
      'tier-b': ['m-3'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['m-5', 'm-7', 'm-8', 'm-9', 'm-10'],
    },
  },
  {
    id: 'food',
    name: 'Food & Comfort Delicacies',
    description: 'Rank global cuisines, street foods, and comfort meals',
    icon: '🍕',
    category: 'Lifestyle',
    title: 'Ultimate Food & Street Cuisine Tier List',
    subtitle: 'Ranked purely by flavor, craving factor, and deliciousness',
    author: 'Foodie Live',
    tiers: [
      { id: 'tier-s', title: 'S - Heavenly (Can eat daily)', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Top Tier Delicious', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Solid Comfort Food', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Good occasionally', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Meh / Overrated', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'fd-1',
        title: 'Wood-Fired Pizza',
        imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80',
        category: 'Italian',
        subtitle: 'Crispy crust & fresh mozzarella',
      },
      {
        id: 'fd-2',
        title: 'Tonkotsu Ramen',
        imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=400&q=80',
        category: 'Japanese',
        subtitle: 'Rich broth & tender chashu',
      },
      {
        id: 'fd-3',
        title: 'Fresh Sushi & Sashimi',
        imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=400&q=80',
        category: 'Japanese',
        subtitle: 'Salmon, tuna, and avocado rolls',
      },
      {
        id: 'fd-4',
        title: 'Street Tacos al Pastor',
        imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=400&q=80',
        category: 'Mexican',
        subtitle: 'Corn tortilla, pineapple & salsa',
      },
      {
        id: 'fd-5',
        title: 'Gourmet Smash Burger',
        imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
        category: 'American',
        subtitle: 'Double patty & melted cheddar',
      },
      {
        id: 'fd-6',
        title: 'Butter Chicken & Garlic Naan',
        imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=400&q=80',
        category: 'Indian',
        subtitle: 'Creamy tomato curry with hot naan',
      },
      {
        id: 'fd-7',
        title: 'Hyderabadi Dum Biryani',
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80',
        category: 'Indian',
        subtitle: 'Aromatic saffron basmati rice',
      },
      {
        id: 'fd-8',
        title: 'Artisan Butter Croissant',
        imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=400&q=80',
        category: 'French Bakery',
        subtitle: 'Flaky, buttery layers',
      },
      {
        id: 'fd-9',
        title: 'Italian Gelato',
        imageUrl: 'https://images.unsplash.com/photo-1560008581-09826d1de69e?auto=format&fit=crop&w=400&q=80',
        category: 'Dessert',
        subtitle: 'Pistachio & dark chocolate',
      },
      {
        id: 'fd-10',
        title: 'Smoked Texas BBQ Ribs',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
        category: 'BBQ',
        subtitle: 'Fall-off-the-bone tender',
      },
    ],
    containers: {
      'tier-s': ['fd-1', 'fd-2'],
      'tier-a': ['fd-3', 'fd-5'],
      'tier-b': ['fd-4'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['fd-6', 'fd-7', 'fd-8', 'fd-9', 'fd-10'],
    },
  },
  {
    id: 'blank',
    name: 'Blank Custom Template',
    description: 'Start from scratch with your own custom tiers and items',
    icon: '✨',
    category: 'Custom',
    title: 'My Custom Tier List',
    subtitle: 'Create, customize, and rank anything you want',
    author: 'Live Streamer',
    tiers: DEFAULT_TIERS,
    items: [],
    containers: {
      'tier-s': [],
      'tier-a': [],
      'tier-b': [],
      'tier-c': [],
      'tier-d': [],
      'tier-f': [],
      POOL: [],
    },
  },
]