import type { ColorPreset, TemplateData, Tier } from './types'

export const EXTERNAL_LINKS = {
  GITHUB_REPO: 'https://github.com/coder-shanks/tier-list-maker-live'
}

export const COLOR_PRESETS: ColorPreset[] = [
  { id: 'crimson', name: 'Ruby S', bg: '#e11d48', text: '#ffffff', border: '#be123c' },
  { id: 'ember', name: 'Flame A', bg: '#ea580c', text: '#ffffff', border: '#c2410c' },
  { id: 'gold', name: 'Solar B', bg: '#d97706', text: '#000000', border: '#b45309' },
  { id: 'mint', name: 'Cyber Mint C', bg: '#059669', text: '#ffffff', border: '#047857' },
  { id: 'cerulean', name: 'Sky Cerulean D', bg: '#0284c7', text: '#ffffff', border: '#0369a1' },
  { id: 'violet', name: 'Royal Violet F', bg: '#7c3aed', text: '#ffffff', border: '#6d28d9' },
  { id: 'slate', name: 'Steel Slate', bg: '#475569', text: '#ffffff', border: '#334155' },
  { id: 'rose', name: 'Neon Rose', bg: '#f43f5e', text: '#ffffff', border: '#e11d48' },
  { id: 'amber', name: 'Pure Amber', bg: '#f59e0b', text: '#000000', border: '#d97706' },
  { id: 'emerald', name: 'Emerald Green', bg: '#10b981', text: '#ffffff', border: '#059669' },
  { id: 'cyan', name: 'Cyan Glow', bg: '#06b6d4', text: '#ffffff', border: '#0891b2' },
  { id: 'indigo', name: 'Deep Indigo', bg: '#4f46e5', text: '#ffffff', border: '#4338ca' },
  { id: 'purple', name: 'Electric Purple', bg: '#9333ea', text: '#ffffff', border: '#7e22ce' },
  { id: 'fuchsia', name: 'Hot Fuchsia', bg: '#c026d3', text: '#ffffff', border: '#a21caf' },
  { id: 'zinc', name: 'Obsidian Black', bg: '#18181b', text: '#ffffff', border: '#27272a' },
  { id: 'neutral', name: 'Architect White', bg: '#e2e8f0', text: '#0f172a', border: '#cbd5e1' },
]

export const DEFAULT_TIERS: Tier[] = [
  { id: 'tier-s', title: 'S', color: '#e11d48', textColor: '#ffffff' },
  { id: 'tier-a', title: 'A', color: '#ea580c', textColor: '#ffffff' },
  { id: 'tier-b', title: 'B', color: '#d97706', textColor: '#000000' },
  { id: 'tier-c', title: 'C', color: '#059669', textColor: '#ffffff' },
  { id: 'tier-d', title: 'D', color: '#0284c7', textColor: '#ffffff' },
  { id: 'tier-f', title: 'F', color: '#7c3aed', textColor: '#ffffff' },
]

export const TEMPLATES: TemplateData[] = [
  {
    id: 'games',
    name: 'Top Video Games',
    description: 'Rank all-time greatest video games across history and genres',
    icon: '🎮',
    category: 'Gaming',
    title: 'All-Time Greatest Video Games Tier List',
    subtitle: 'Ranked live based on gameplay, story, innovation, and replayability',
    author: 'Live Streamer',
    tiers: [
      { id: 'tier-s', title: 'GOAT (Masterpiece)', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'Must Play (Elite)', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'Great Fun', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'Decent / Average', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'Overrated / Meh', color: '#06b6d4', textColor: '#ffffff' },
      { id: 'tier-f', title: 'Not For Me', color: '#8b5cf6', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'g-1',
        title: 'Elden Ring',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg',
        category: 'Action RPG',
        subtitle: 'FromSoftware (2022)',
      },
      {
        id: 'g-2',
        title: 'Zelda: Tears of the Kingdom',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fb/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg',
        category: 'Adventure',
        subtitle: 'Nintendo (2023)',
      },
      {
        id: 'g-3',
        title: "Baldur's Gate 3",
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/12/Baldur%27s_Gate_III_cover_art.jpg',
        category: 'CRPG',
        subtitle: 'Larian Studios (2023)',
      },
      {
        id: 'g-4',
        title: 'Grand Theft Auto V',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png',
        category: 'Open World',
        subtitle: 'Rockstar Games (2013)',
      },
      {
        id: 'g-5',
        title: 'The Witcher 3: Wild Hunt',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg',
        category: 'RPG',
        subtitle: 'CD Projekt RED (2015)',
      },
      {
        id: 'g-6',
        title: 'Cyberpunk 2077',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg',
        category: 'Sci-Fi RPG',
        subtitle: 'CD Projekt RED (2020)',
      },
      {
        id: 'g-7',
        title: 'Minecraft',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/51/Minecraft_cover.png',
        category: 'Sandbox',
        subtitle: 'Mojang (2011)',
      },
      {
        id: 'g-8',
        title: 'Red Dead Redemption 2',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg',
        category: 'Action Adventure',
        subtitle: 'Rockstar Games (2018)',
      },
      {
        id: 'g-9',
        title: 'God of War Ragnarök',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg',
        category: 'Action',
        subtitle: 'Santa Monica (2022)',
      },
      {
        id: 'g-10',
        title: 'Hollow Knight',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/0/04/Hollow_Knight_first_cover_art.webp',
        category: 'Metroidvania',
        subtitle: 'Team Cherry (2017)',
      },
      {
        id: 'g-11',
        title: 'Dark Souls III',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/bb/Dark_souls_3_cover_art.jpg',
        category: 'Souls-like',
        subtitle: 'FromSoftware (2016)',
      },
      {
        id: 'g-12',
        title: 'Super Mario Odyssey',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg',
        category: 'Platformer',
        subtitle: 'Nintendo (2017)',
      },
      {
        id: 'g-13',
        title: 'Portal 2',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Portal2cover.jpg',
        category: 'Puzzle',
        subtitle: 'Valve (2011)',
      },
      {
        id: 'g-14',
        title: 'Skyrim',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png',
        category: 'Fantasy RPG',
        subtitle: 'Bethesda (2011)',
      },
    ],
    containers: {
      'tier-s': ['g-1', 'g-4'],
      'tier-a': ['g-2', 'g-3'],
      'tier-b': ['g-5'],
      'tier-c': [],
      'tier-d': [],
      'tier-f': [],
      POOL: ['g-6', 'g-7', 'g-8', 'g-9', 'g-10', 'g-11', 'g-12', 'g-13', 'g-14'],
    },
  },
  {
    id: 'anime',
    name: 'Anime Masterpieces',
    description: 'Rank iconic anime series, shonen hits, and timeless classics',
    icon: '⚔️',
    category: 'Anime',
    title: 'Top Anime & Manga Series Tier List',
    subtitle: 'Ranked on story arcs, animation quality, world-building, and character growth',
    author: 'Anime Otaku',
    tiers: [
      { id: 'tier-s', title: 'S - God Tier / Masterpiece', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Peak Anime / Must Watch', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Really Great / High Fun', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Good / Solid Watch', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Mid / Overhyped', color: '#06b6d4', textColor: '#ffffff' },
      { id: 'tier-f', title: 'F - Dropped / Not For Me', color: '#8b5cf6', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'ani-1',
        title: 'Attack on Titan',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Shingeki_no_Kyojin_manga_volume_1.jpg',
        category: 'Dark Fantasy',
        subtitle: 'Wit Studio / MAPPA',
      },
      {
        id: 'ani-2',
        title: 'Death Note',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6f/Death_Note_Vol_1.jpg',
        category: 'Psychological',
        subtitle: 'Madhouse',
      },
      {
        id: 'ani-3',
        title: 'Fullmetal Alchemist: Brotherhood',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7e/Fullmetal_Alchemist_Brotherhood_key_visual.png',
        category: 'Action Fantasy',
        subtitle: 'Bones',
      },
      {
        id: 'ani-4',
        title: 'Demon Slayer',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/0/09/Demon_Slayer_-_Kimetsu_no_Yaiba%2C_volume_1.jpg',
        category: 'Shonen Action',
        subtitle: 'ufotable',
      },
      {
        id: 'ani-5',
        title: 'Jujutsu Kaisen',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/4/46/Jujutsu_kaisen.jpg',
        category: 'Supernatural',
        subtitle: 'MAPPA',
      },
      {
        id: 'ani-6',
        title: 'One Piece',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/9/90/One_Piece%2C_Volume_61_Cover_%28Japanese%29.jpg',
        category: 'Adventure',
        subtitle: 'Toei Animation',
      },
      {
        id: 'ani-7',
        title: 'Hunter x Hunter',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0f/Hunter_x_Hunter_cover_-_vol1.jpg',
        category: 'Shonen',
        subtitle: 'Madhouse (2011)',
      },
      {
        id: 'ani-8',
        title: 'Chainsaw Man',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/2/24/Chainsawman_volume_1_cover.jpg',
        category: 'Action / Dark Fantasy',
        subtitle: 'MAPPA',
      },
      {
        id: 'ani-9',
        title: 'Naruto Shippuden',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/9/94/NarutoCoverTankobon1.jpg',
        category: 'Ninja Shonen',
        subtitle: 'Studio Pierrot',
      },
      {
        id: 'ani-10',
        title: 'Spirited Away',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png',
        category: 'Movie',
        subtitle: 'Studio Ghibli / Miyazaki',
      },
      {
        id: 'ani-11',
        title: 'Vinland Saga',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c8/Vinland_Saga_volume_01_cover.jpg',
        category: 'Historical Action',
        subtitle: 'Wit / MAPPA',
      },
      {
        id: 'ani-12',
        title: 'Neon Genesis Evangelion',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Neon_Genesis_Evangelion_original_soundtrack_cover.jpg',
        category: 'Mecha / Sci-Fi',
        subtitle: 'Gainax / Hideaki Anno',
      },
    ],
    containers: {
      'tier-s': ['ani-1', 'ani-3'],
      'tier-a': ['ani-2', 'ani-6'],
      'tier-b': ['ani-4', 'ani-5'],
      'tier-c': [],
      'tier-d': [],
      'tier-f': [],
      POOL: ['ani-7', 'ani-8', 'ani-9', 'ani-10', 'ani-11', 'ani-12'],
    },
  },
  {
    id: 'superheroes',
    name: 'Superheroes & Comics',
    description: 'Rank iconic comic superheroes, antiheroes, and villains',
    icon: '🦸',
    category: 'Entertainment',
    title: 'Greatest Superheroes Tier List',
    subtitle: 'Ranked on powers, comic legacy, villains, lore, and impact',
    author: 'Comic Fan',
    tiers: [
      { id: 'tier-s', title: 'S - Apex Legends', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Top Tier Heroes', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Solid Powerhouses', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Good Support', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Low Tier / Meh', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'sh-1',
        title: 'Batman',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c7/Batman_Infobox.jpg',
        category: 'DC',
        subtitle: 'The Dark Knight',
      },
      {
        id: 'sh-2',
        title: 'Spider-Man',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/2/21/Web_of_Spider-Man_Vol_1_129-1.png',
        category: 'Marvel',
        subtitle: 'Friendly Neighborhood Hero',
      },
      {
        id: 'sh-3',
        title: 'Iron Man',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Iron_Man_bleeding_edge.jpg',
        category: 'Marvel',
        subtitle: 'Tony Stark / MCU Anchor',
      },
      {
        id: 'sh-4',
        title: 'Superman',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/3/35/Supermanflying.png',
        category: 'DC',
        subtitle: 'Man of Steel',
      },
      {
        id: 'sh-5',
        title: 'Wolverine',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5d/Wolverine_%28James_%27Logan%27_Howlett%29.png',
        category: 'Marvel',
        subtitle: 'Weapon X / X-Men',
      },
      {
        id: 'sh-6',
        title: 'The Joker',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/9/98/Joker_%28DC_Comics_character%29.jpg',
        category: 'DC Villain',
        subtitle: 'Clown Prince of Crime',
      },
      {
        id: 'sh-7',
        title: 'Deadpool',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/bd/Deadpool.jpg',
        category: 'Marvel Antihero',
        subtitle: 'Merc with a Mouth',
      },
      {
        id: 'sh-8',
        title: 'Wonder Woman',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/9/93/Wonder_Woman.jpg',
        category: 'DC',
        subtitle: 'Princess of Themyscira',
      },
      {
        id: 'sh-9',
        title: 'Thor',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/7/79/Thor_Marvel_Comics.png',
        category: 'Marvel',
        subtitle: 'God of Thunder',
      },
      {
        id: 'sh-10',
        title: 'Thanos',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Thanos_Infinity_War.jpg',
        category: 'Marvel Villain',
        subtitle: 'The Mad Titan',
      },
      {
        id: 'sh-11',
        title: 'Captain America',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/9/91/CaptainAmerica109.jpg',
        category: 'Marvel',
        subtitle: 'First Avenger',
      },
      {
        id: 'sh-12',
        title: 'The Flash',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Flash_vol_5_1.png',
        category: 'DC',
        subtitle: 'Fastest Man Alive',
      },
    ],
    containers: {
      'tier-s': ['sh-1', 'sh-2'],
      'tier-a': ['sh-3', 'sh-4', 'sh-6'],
      'tier-b': ['sh-5', 'sh-7'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['sh-8', 'sh-9', 'sh-10', 'sh-11', 'sh-12'],
    },
  },
  {
    id: 'football',
    name: 'Football / Soccer Legends',
    description: 'Rank iconic football players of all time',
    icon: '⚽',
    category: 'Sports',
    title: 'Football GOATs Tier List',
    subtitle: 'Ranked on individual skill, trophies, longevity, and historic moments',
    author: 'Live Streamer',
    tiers: [
      { id: 'tier-s', title: 'The GOATs (S-Tier)', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'All-Time Legends', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'World Class Elite', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'Iconic Stars', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'Great Players', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'fb-1',
        title: 'Lionel Messi',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Lionel_Messi_20180626.jpg/440px-Lionel_Messi_20180626.jpg',
        category: 'Forward',
        subtitle: '8x Ballon d’Or & World Cup',
      },
      {
        id: 'fb-2',
        title: 'Cristiano Ronaldo',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis%2C_September_2023_%28cropped%29.jpg/440px-Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis%2C_September_2023_%28cropped%29.jpg',
        category: 'Forward',
        subtitle: '5x Ballon d’Or & 5x UCL',
      },
      {
        id: 'fb-3',
        title: 'Pelé',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Pel%C3%A9_by_John_Mathew_Smith_2008.jpg/440px-Pel%C3%A9_by_John_Mathew_Smith_2008.jpg',
        category: 'Forward',
        subtitle: '3x World Cup Champion',
      },
      {
        id: 'fb-4',
        title: 'Diego Maradona',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Maradona-Mundial_86_con_la_copa.JPG/440px-Maradona-Mundial_86_con_la_copa.JPG',
        category: 'Playmaker',
        subtitle: '1986 World Cup Champion',
      },
      {
        id: 'fb-5',
        title: 'Zinedine Zidane',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg/440px-Zinedine_Zidane_by_Tasnim_03.jpg',
        category: 'Midfielder',
        subtitle: 'Ballon d’Or & World Cup',
      },
      {
        id: 'fb-6',
        title: 'Ronaldinho',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ronaldinho_Ga%C3%BAcho_2019.jpg/440px-Ronaldinho_Ga%C3%BAcho_2019.jpg',
        category: 'Winger',
        subtitle: 'Joga Bonito Maestro',
      },
      {
        id: 'fb-7',
        title: 'Kylian Mbappé',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/2019-07-17_SG_Dynamo_Dresden_vs._Paris_Saint-Germain_by_Sandro_Halank%E2%80%93129_%28cropped%29.jpg/440px-2019-07-17_SG_Dynamo_Dresden_vs._Paris_Saint-Germain_by_Sandro_Halank%E2%80%93129_%28cropped%29.jpg',
        category: 'Forward',
        subtitle: 'World Cup Winner & Golden Boot',
      },
      {
        id: 'fb-8',
        title: 'Erling Haaland',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Erling_Haaland_2023_%28cropped-v2%29.jpg/440px-Erling_Haaland_2023_%28cropped-v2%29.jpg',
        category: 'Striker',
        subtitle: 'Treble Winner & Record Scorer',
      },
      {
        id: 'fb-9',
        title: 'Luka Modrić',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Luka_Modri%C4%87_Manchester_City_v_Real_Madrid%2C_17_May_2023.jpg/440px-Luka_Modri%C4%87_Manchester_City_v_Real_Madrid%2C_17_May_2023.jpg',
        category: 'Midfielder',
        subtitle: 'Ballon d’Or & 6x UCL',
      },
      {
        id: 'fb-10',
        title: 'Andres Iniesta',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Andr%C3%A9s_Iniesta.jpg/440px-Andr%C3%A9s_Iniesta.jpg',
        category: 'Midfielder',
        subtitle: 'World Cup Final Match Winner',
      },
      {
        id: 'fb-11',
        title: 'Ronaldo Nazário (R9)',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Ronaldo_2018.jpg/440px-Ronaldo_2018.jpg',
        category: 'Striker',
        subtitle: 'El Fenómeno',
      },
      {
        id: 'fb-12',
        title: 'Thierry Henry',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Thierry_Henry_2011.jpg/440px-Thierry_Henry_2011.jpg',
        category: 'Forward',
        subtitle: 'Arsenal Invincibles Legend',
      },
    ],
    containers: {
      'tier-s': ['fb-1', 'fb-2'],
      'tier-a': ['fb-3', 'fb-4'],
      'tier-b': ['fb-5', 'fb-6'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['fb-7', 'fb-8', 'fb-9', 'fb-10', 'fb-11', 'fb-12'],
    },
  },
  {
    id: 'nba',
    name: 'NBA Basketball Legends',
    description: 'Rank basketball icons, champions, and greatest scorers',
    icon: '🏀',
    category: 'Sports',
    title: 'NBA Greatest Players Tier List',
    subtitle: 'Ranked on rings, MVPs, scoring dominance, and clutch legacy',
    author: 'Hoops Live',
    tiers: [
      { id: 'tier-s', title: 'S - The Absolute GOATs', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Top 10 All-Time', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Dominant Champions', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Hall of Fame Elite', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Franchise Superstars', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'nba-1',
        title: 'Michael Jordan',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Michael_Jordan_in_2014.jpg/440px-Michael_Jordan_in_2014.jpg',
        category: 'Shooting Guard',
        subtitle: '6x Champion & 6x Finals MVP',
      },
      {
        id: 'nba-2',
        title: 'LeBron James',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg/440px-LeBron_James_%2851959977144%29_%28cropped2%29.jpg',
        category: 'Small Forward',
        subtitle: 'All-Time Scoring Leader & 4x Ring',
      },
      {
        id: 'nba-3',
        title: 'Kobe Bryant',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Kobe_Bryant_2014.jpg/440px-Kobe_Bryant_2014.jpg',
        category: 'Shooting Guard',
        subtitle: '5x Champion / Mamba Mentality',
      },
      {
        id: 'nba-4',
        title: 'Stephen Curry',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Stephen_Curry_dribbling_2016_%28cropped%29.jpg/440px-Stephen_Curry_dribbling_2016_%28cropped%29.jpg',
        category: 'Point Guard',
        subtitle: 'Greatest Shooter in History',
      },
      {
        id: 'nba-5',
        title: "Shaquille O'Neal",
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Shaquille_O%27Neal_2017.jpg/440px-Shaquille_O%27Neal_2017.jpg',
        category: 'Center',
        subtitle: 'Most Dominant Center',
      },
      {
        id: 'nba-6',
        title: 'Magic Johnson',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Magic_Johnson_1987.jpg/440px-Magic_Johnson_1987.jpg',
        category: 'Point Guard',
        subtitle: 'Showtime Lakers Leader',
      },
      {
        id: 'nba-7',
        title: 'Larry Bird',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Larry_Bird_Lipofsky.jpg/440px-Larry_Bird_Lipofsky.jpg',
        category: 'Forward',
        subtitle: '3x MVP & Celtics Legend',
      },
      {
        id: 'nba-8',
        title: 'Kareem Abdul-Jabbar',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Kareem_Abdul-Jabbar_May_2014.jpg/440px-Kareem_Abdul-Jabbar_May_2014.jpg',
        category: 'Center',
        subtitle: '6x MVP & Unstoppable Skyhook',
      },
      {
        id: 'nba-9',
        title: 'Kevin Durant',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Kevin_Durant_2021_%28cropped%29.jpg/440px-Kevin_Durant_2021_%28cropped%29.jpg',
        category: 'Forward',
        subtitle: '2x Finals MVP & Pure Scorer',
      },
      {
        id: 'nba-10',
        title: 'Tim Duncan',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Tim_Duncan_cropped.jpg/440px-Tim_Duncan_cropped.jpg',
        category: 'Power Forward',
        subtitle: 'The Big Fundamental / 5x Ring',
      },
    ],
    containers: {
      'tier-s': ['nba-1', 'nba-2'],
      'tier-a': ['nba-3', 'nba-4', 'nba-5'],
      'tier-b': ['nba-6', 'nba-8'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['nba-7', 'nba-9', 'nba-10'],
    },
  },
  {
    id: 'music',
    name: 'Legendary Music Artists',
    description: 'Rank iconic music artists, legendary bands, and pop icons',
    icon: '🎵',
    category: 'Entertainment',
    title: 'Greatest Music Artists & Bands Tier List',
    subtitle: 'Ranked on vocal ability, songwriting, cultural impact, and timeless hits',
    author: 'Music Curator',
    tiers: [
      { id: 'tier-s', title: 'S - Musical Immortals', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Iconic Legends', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Superstars & Hits', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Solid Artists', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Overrated / Niche', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'mus-1',
        title: 'The Beatles',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/The_Fabs.JPG/440px-The_Fabs.JPG',
        category: 'Rock',
        subtitle: 'Lennon, McCartney, Harrison, Starr',
      },
      {
        id: 'mus-2',
        title: 'Michael Jackson',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Michael_Jackson_in_1988.jpg/440px-Michael_Jackson_in_1988.jpg',
        category: 'Pop',
        subtitle: 'King of Pop / Thriller',
      },
      {
        id: 'mus-3',
        title: 'Queen',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Queen_Band.jpg/440px-Queen_Band.jpg',
        category: 'Rock',
        subtitle: 'Freddie Mercury & Brian May',
      },
      {
        id: 'mus-4',
        title: 'Daft Punk',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Daft_Punk_in_2013.jpg/440px-Daft_Punk_in_2013.jpg',
        category: 'Electronic',
        subtitle: 'French House Pioneers',
      },
      {
        id: 'mus-5',
        title: 'Eminem',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Eminem_2021.jpg/440px-Eminem_2021.jpg',
        category: 'Hip-Hop',
        subtitle: 'Rap God / 15x Grammy Winner',
      },
      {
        id: 'mus-6',
        title: 'Kendrick Lamar',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Pulitzer2018-portraits-kendrick-lamar.jpg/440px-Pulitzer2018-portraits-kendrick-lamar.jpg',
        category: 'Hip-Hop',
        subtitle: 'Pulitzer Prize Winner',
      },
      {
        id: 'mus-7',
        title: 'Taylor Swift',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/191125_Taylor_Swift_at_the_2019_American_Music_Awards.png/440px-191125_Taylor_Swift_at_the_2019_American_Music_Awards.png',
        category: 'Pop / Folk',
        subtitle: 'Eras Tour Record Breaker',
      },
      {
        id: 'mus-8',
        title: 'Pink Floyd',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Pink_Floyd_-_all_members.jpg/440px-Pink_Floyd_-_all_members.jpg',
        category: 'Prog Rock',
        subtitle: 'The Dark Side of the Moon',
      },
      {
        id: 'mus-9',
        title: 'Nirvana',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Nirvana_around_1992.jpg/440px-Nirvana_around_1992.jpg',
        category: 'Grunge',
        subtitle: 'Kurt Cobain / Nevermind',
      },
      {
        id: 'mus-10',
        title: 'Beyoncé',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Beyonc%C3%A9_at_The_Lion_King_European_Premiere_2019.png/440px-Beyonc%C3%A9_at_The_Lion_King_European_Premiere_2019.png',
        category: 'R&B / Pop',
        subtitle: 'Most Awarded Grammy Artist',
      },
    ],
    containers: {
      'tier-s': ['mus-1', 'mus-2'],
      'tier-a': ['mus-3', 'mus-4'],
      'tier-b': ['mus-5', 'mus-6'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['mus-7', 'mus-8', 'mus-9', 'mus-10'],
    },
  },
  {
    id: 'tech',
    name: 'Tech & Programming',
    description: 'Rank programming languages, frameworks, and developer tools',
    icon: '💻',
    category: 'Development',
    title: 'Developer Tech Stack Tier List',
    subtitle: 'Ranked by developer experience, performance, ecosystem, and joy',
    author: 'Tech Creator',
    tiers: [
      { id: 'tier-s', title: 'S - God Tier / Daily Driver', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - S Tier Potential / Love It', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Solid & Reliable', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Fine for Legacy', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Painful / Avoid', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 't-1',
        title: 'TypeScript',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/512px-Typescript_logo_2020.svg.png',
        category: 'Language',
        subtitle: 'Typed JavaScript',
      },
      {
        id: 't-2',
        title: 'Rust',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Rust_programming_language_black_logo.svg/512px-Rust_programming_language_black_logo.svg.png',
        category: 'Systems',
        subtitle: 'Blazing Fast & Memory Safe',
      },
      {
        id: 't-3',
        title: 'Python',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/512px-Python-logo-notext.svg.png',
        category: 'Language',
        subtitle: 'AI & Data Science Standard',
      },
      {
        id: 't-4',
        title: 'Go (Golang)',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Go_Logo_Blue.svg/512px-Go_Logo_Blue.svg.png',
        category: 'Backend',
        subtitle: 'Simple & Robust Concurrency',
      },
      {
        id: 't-5',
        title: 'React',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/512px-React-icon.svg.png',
        category: 'UI Library',
        subtitle: 'Component Ecosystem King',
      },
      {
        id: 't-6',
        title: 'Next.js',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Nextjs-logo.svg/512px-Nextjs-logo.svg.png',
        category: 'Framework',
        subtitle: 'Full-Stack React Framework',
      },
      {
        id: 't-7',
        title: 'PostgreSQL',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/512px-Postgresql_elephant.svg.png',
        category: 'Database',
        subtitle: 'Relational DB Gold Standard',
      },
      {
        id: 't-8',
        title: 'Docker',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Docker_%28container_engine%29_logo.svg/512px-Docker_%28container_engine%29_logo.svg.png',
        category: 'DevOps',
        subtitle: 'Containers Everywhere',
      },
      {
        id: 't-9',
        title: 'Tailwind CSS',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/512px-Tailwind_CSS_Logo.svg.png',
        category: 'Styling',
        subtitle: 'Utility-First CSS',
      },
      {
        id: 't-10',
        title: 'Redis',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Redis_Logo.svg/512px-Redis_Logo.svg.png',
        category: 'Cache',
        subtitle: 'Ultra Fast In-Memory Store',
      },
      {
        id: 't-11',
        title: 'C++',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/512px-ISO_C%2B%2B_Logo.svg.png',
        category: 'Language',
        subtitle: 'High Performance & Engines',
      },
      {
        id: 't-12',
        title: 'GraphQL',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/GraphQL_Logo.svg/512px-GraphQL_Logo.svg.png',
        category: 'API',
        subtitle: 'Declarative Data Fetching',
      },
    ],
    containers: {
      'tier-s': ['t-1', 't-5'],
      'tier-a': ['t-2', 't-7'],
      'tier-b': ['t-3', 't-8'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['t-4', 't-6', 't-9', 't-10', 't-11', 't-12'],
    },
  },
  {
    id: 'tv_shows',
    name: 'Binge-Worthy TV Series',
    description: 'Rank the most gripping, critically acclaimed television series',
    icon: '📺',
    category: 'Entertainment',
    title: 'All-Time Greatest TV Shows Tier List',
    subtitle: 'Ranked on storytelling, character arcs, plot twists, and series finales',
    author: 'Binge Watcher',
    tiers: [
      { id: 'tier-s', title: 'S - Peak Television', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Masterpiece Seasons', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Highly Addictive', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Good Casual Watch', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Fell Off / Bad Ending', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'tv-1',
        title: 'Breaking Bad',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/6/61/Breaking_Bad_title_card.png',
        category: 'Drama / Crime',
        subtitle: 'Vince Gilligan (AMC)',
      },
      {
        id: 'tv-2',
        title: 'Game of Thrones',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e8/Game_of_Thrones_Season_1.jpg',
        category: 'Epic Fantasy',
        subtitle: 'HBO (2011–2019)',
      },
      {
        id: 'tv-3',
        title: 'The Sopranos',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cb/The_Sopranos_title_card.png',
        category: 'Crime Drama',
        subtitle: 'David Chase (HBO)',
      },
      {
        id: 'tv-4',
        title: 'Stranger Things',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Stranger_Things_logo.png/440px-Stranger_Things_logo.png',
        category: 'Sci-Fi / Horror',
        subtitle: 'Duffer Brothers (Netflix)',
      },
      {
        id: 'tv-5',
        title: 'Succession',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/0/05/Succession_title_card.png',
        category: 'Satire / Drama',
        subtitle: 'Jesse Armstrong (HBO)',
      },
      {
        id: 'tv-6',
        title: 'The Last of Us',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c2/The_Last_of_Us_TV_series_logo.png',
        category: 'Post-Apocalyptic',
        subtitle: 'Craig Mazin & Neil Druckmann',
      },
      {
        id: 'tv-7',
        title: 'Arcane',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2f/Arcane_Title_Text.png',
        category: 'Animation / Sci-Fi',
        subtitle: 'Fortiche / Riot Games',
      },
      {
        id: 'tv-8',
        title: 'Better Call Saul',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Better_Call_Saul_logo.png',
        category: 'Legal Crime',
        subtitle: 'Peter Gould & Vince Gilligan',
      },
      {
        id: 'tv-9',
        title: 'The Wire',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/54/The_Wire_title_card.jpg',
        category: 'Crime Drama',
        subtitle: 'David Simon (HBO)',
      },
      {
        id: 'tv-10',
        title: 'Dark',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Dark_Netflix_Logo.svg/440px-Dark_Netflix_Logo.svg.png',
        category: 'Sci-Fi Mystery',
        subtitle: 'Baran bo Odar (Netflix)',
      },
    ],
    containers: {
      'tier-s': ['tv-1', 'tv-3'],
      'tier-a': ['tv-5', 'tv-7', 'tv-8'],
      'tier-b': ['tv-4', 'tv-6'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['tv-2', 'tv-9', 'tv-10'],
    },
  },
  {
    id: 'pokemon',
    name: 'Pokémon All-Stars',
    description: 'Rank iconic, legendary, and fan-favorite Pokémon',
    icon: '⚡',
    category: 'Gaming',
    title: 'Ultimate Pokémon Tier List',
    subtitle: 'Ranked on battle strength, design, nostalgia, and versatility',
    author: 'Pokémon Trainer',
    tiers: [
      { id: 'tier-s', title: 'S - God Tier / Legendary', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Elite Champions', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Great Battlers', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Decent Companions', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Weak / Forgettable', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'pok-1',
        title: 'Pikachu',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a6/Pok%C3%A9mon_Pikachu_art.png',
        category: 'Electric',
        subtitle: 'Gen I #0025 Mascot',
      },
      {
        id: 'pok-2',
        title: 'Charizard',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1f/Pok%C3%A9mon_Charizard_art.png',
        category: 'Fire / Flying',
        subtitle: 'Gen I #0006 Starter Icon',
      },
      {
        id: 'pok-3',
        title: 'Mewtwo',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5c/Pok%C3%A9mon_Mewtwo_art.png',
        category: 'Psychic',
        subtitle: 'Gen I #0150 Legendary',
      },
      {
        id: 'pok-4',
        title: 'Gengar',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/53/Pok%C3%A9mon_Gengar_art.png',
        category: 'Ghost / Poison',
        subtitle: 'Gen I #0094 Shadow Pokémon',
      },
      {
        id: 'pok-5',
        title: 'Lucario',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d7/Lucario.png',
        category: 'Fighting / Steel',
        subtitle: 'Gen IV #0448 Aura Guardian',
      },
      {
        id: 'pok-6',
        title: 'Rayquaza',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Pok%C3%A9mon_Rayquaza_art.png',
        category: 'Dragon / Flying',
        subtitle: 'Gen III #0384 Sky High Pokémon',
      },
      {
        id: 'pok-7',
        title: 'Eevee',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Pok%C3%A9mon_Eevee_art.png',
        category: 'Normal',
        subtitle: 'Gen I #0133 Evolution Master',
      },
      {
        id: 'pok-8',
        title: 'Greninja',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/56/Greninja.png',
        category: 'Water / Dark',
        subtitle: 'Gen VI #0658 Ninja Star',
      },
      {
        id: 'pok-9',
        title: 'Snorlax',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Pok%C3%A9mon_Snorlax_art.png',
        category: 'Normal',
        subtitle: 'Gen I #0143 Sleeping Giant',
      },
      {
        id: 'pok-10',
        title: 'Bulbasaur',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/2/21/0001Bulbasaur.png',
        category: 'Grass / Poison',
        subtitle: 'Gen I #0001 First Pokémon',
      },
    ],
    containers: {
      'tier-s': ['pok-2', 'pok-3'],
      'tier-a': ['pok-1', 'pok-5'],
      'tier-b': ['pok-4', 'pok-7'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['pok-6', 'pok-8', 'pok-9', 'pok-10'],
    },
  },
  {
    id: 'fast_food',
    name: 'Fast Food & Quick Bites',
    description: 'Rank popular fast food chains, burgers, chicken, and snacks',
    icon: '🍔',
    category: 'Lifestyle',
    title: 'Fast Food Chains Tier List',
    subtitle: 'Ranked on fries, burger quality, menu consistency, and sauce game',
    author: 'Snack Reviewer',
    tiers: [
      { id: 'tier-s', title: 'S - God Tier Craving', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Always Hits', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Solid Meal', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Only When Desperate', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Never Again', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'ff-1',
        title: "McDonald's",
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/McDonald%27s_Golden_Arches.svg/440px-McDonald%27s_Golden_Arches.svg.png',
        category: 'Burgers & Fries',
        subtitle: 'Famous Golden Fries',
      },
      {
        id: 'ff-2',
        title: 'In-N-Out Burger',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/In-N-Out_Burger_logo.svg/440px-In-N-Out_Burger_logo.svg.png',
        category: 'Burgers',
        subtitle: 'Double-Double Animal Style',
      },
      {
        id: 'ff-3',
        title: 'Chick-fil-A',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Chick-fil-A_Logo.svg/440px-Chick-fil-A_Logo.svg.png',
        category: 'Chicken',
        subtitle: 'Waffle Fries & Signature Sauce',
      },
      {
        id: 'ff-4',
        title: 'Taco Bell',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Taco_Bell_2016.svg/440px-Taco_Bell_2016.svg.png',
        category: 'Tex-Mex',
        subtitle: 'Crunchwrap Supreme & Baja Blast',
      },
      {
        id: 'ff-5',
        title: "Wendy's",
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Wendy%27s_full_logo_2012.svg/440px-Wendy%27s_full_logo_2012.svg.png',
        category: 'Burgers',
        subtitle: 'Baconator & Frosty',
      },
      {
        id: 'ff-6',
        title: 'Subway',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Subway_2016_logo.svg/440px-Subway_2016_logo.svg.png',
        category: 'Sandwiches',
        subtitle: 'Custom Subs & Cookies',
      },
      {
        id: 'ff-7',
        title: 'KFC',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/KFC_logo.svg/440px-KFC_logo.svg.png',
        category: 'Chicken',
        subtitle: 'Original Recipe Fried Chicken',
      },
      {
        id: 'ff-8',
        title: "Domino's Pizza",
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Dominos_pizza_logo.svg/440px-Dominos_pizza_logo.svg.png',
        category: 'Pizza',
        subtitle: 'Cheesy Bread & Fast Delivery',
      },
      {
        id: 'ff-9',
        title: 'Five Guys',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Five_Guys_Burgers_and_Fries_logo.svg/440px-Five_Guys_Burgers_and_Fries_logo.svg.png',
        category: 'Burgers',
        subtitle: 'Fresh Patties & Bag of Fries',
      },
      {
        id: 'ff-10',
        title: 'Popeyes',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Popeyes_logo_2020.svg/440px-Popeyes_logo_2020.svg.png',
        category: 'Chicken',
        subtitle: 'Spicy Chicken Sandwich',
      },
    ],
    containers: {
      'tier-s': ['ff-2', 'ff-3'],
      'tier-a': ['ff-1', 'ff-10'],
      'tier-b': ['ff-4', 'ff-9'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['ff-5', 'ff-6', 'ff-7', 'ff-8'],
    },
  },
  {
    id: 'movies',
    name: 'Iconic Movies',
    description: 'Rank cinema masterpieces and blockbusters',
    icon: '🎬',
    category: 'Entertainment',
    title: 'Greatest Movies of All Time Tier List',
    subtitle: 'Ranked by storytelling, cinematography, acting, and rewatchability',
    author: 'Film Buff',
    tiers: [
      { id: 'tier-s', title: 'S - Cinema Perfection', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Absolute Classic', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Great Film', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Good Weekend Watch', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Disappointing', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'm-1',
        title: 'The Dark Knight',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg',
        category: 'Action',
        subtitle: 'Christopher Nolan (2008)',
      },
      {
        id: 'm-2',
        title: 'Interstellar',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg',
        category: 'Sci-Fi',
        subtitle: 'Christopher Nolan (2014)',
      },
      {
        id: 'm-3',
        title: 'Inception',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg',
        category: 'Sci-Fi / Thriller',
        subtitle: 'Christopher Nolan (2010)',
      },
      {
        id: 'm-4',
        title: 'The Godfather',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg',
        category: 'Crime Drama',
        subtitle: 'Francis Ford Coppola (1972)',
      },
      {
        id: 'm-5',
        title: 'Pulp Fiction',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg',
        category: 'Neo-Noir',
        subtitle: 'Quentin Tarantino (1994)',
      },
      {
        id: 'm-6',
        title: 'The Matrix',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg',
        category: 'Sci-Fi Action',
        subtitle: 'The Wachowskis (1999)',
      },
      {
        id: 'm-7',
        title: 'Oppenheimer',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg',
        category: 'Biographical',
        subtitle: 'Christopher Nolan (2023)',
      },
      {
        id: 'm-8',
        title: 'Parasite',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png',
        category: 'Thriller / Satire',
        subtitle: 'Bong Joon-ho (2019)',
      },
      {
        id: 'm-9',
        title: 'Gladiator',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png',
        category: 'Historical Epic',
        subtitle: 'Ridley Scott (2000)',
      },
      {
        id: 'm-10',
        title: 'Fight Club',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg',
        category: 'Drama / Mystery',
        subtitle: 'David Fincher (1999)',
      },
    ],
    containers: {
      'tier-s': ['m-1', 'm-2'],
      'tier-a': ['m-4', 'm-6'],
      'tier-b': ['m-3'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['m-5', 'm-7', 'm-8', 'm-9', 'm-10'],
    },
  },
  {
    id: 'food',
    name: 'Food & Comfort Delicacies',
    description: 'Rank global cuisines, street foods, and comfort meals',
    icon: '🍕',
    category: 'Lifestyle',
    title: 'Ultimate Food & Street Cuisine Tier List',
    subtitle: 'Ranked purely by flavor, craving factor, and deliciousness',
    author: 'Foodie Live',
    tiers: [
      { id: 'tier-s', title: 'S - Heavenly (Can eat daily)', color: '#ef4444', textColor: '#ffffff' },
      { id: 'tier-a', title: 'A - Top Tier Delicious', color: '#f97316', textColor: '#ffffff' },
      { id: 'tier-b', title: 'B - Solid Comfort Food', color: '#f59e0b', textColor: '#000000' },
      { id: 'tier-c', title: 'C - Good occasionally', color: '#10b981', textColor: '#ffffff' },
      { id: 'tier-d', title: 'D - Meh / Overrated', color: '#06b6d4', textColor: '#ffffff' },
    ],
    items: [
      {
        id: 'fd-1',
        title: 'Wood-Fired Pizza',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/440px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        category: 'Italian',
        subtitle: 'Crispy crust & fresh mozzarella',
      },
      {
        id: 'fd-2',
        title: 'Tonkotsu Ramen',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Shoyu_Ramen.jpg/440px-Shoyu_Ramen.jpg',
        category: 'Japanese',
        subtitle: 'Rich pork broth & chashu',
      },
      {
        id: 'fd-3',
        title: 'Fresh Sushi & Sashimi',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sushi_platter.jpg/440px-Sushi_platter.jpg',
        category: 'Japanese',
        subtitle: 'Salmon, tuna, and nigiri',
      },
      {
        id: 'fd-4',
        title: 'Street Tacos al Pastor',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/001_Tacos_de_carnitas%2C_tianguis_de_los_domingos%2C_Tepotzotl%C3%A1n.jpg/440px-001_Tacos_de_carnitas%2C_tianguis_de_los_domingos%2C_Tepotzotl%C3%A1n.jpg',
        category: 'Mexican',
        subtitle: 'Corn tortilla, pineapple & salsa',
      },
      {
        id: 'fd-5',
        title: 'Gourmet Smash Burger',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Hamburger_%28black_bg%29.jpg/440px-Hamburger_%28black_bg%29.jpg',
        category: 'American',
        subtitle: 'Crispy edges & melted cheddar',
      },
      {
        id: 'fd-6',
        title: 'Butter Chicken & Naan',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Chicken_makhani.jpg/440px-Chicken_makhani.jpg',
        category: 'Indian',
        subtitle: 'Rich creamy tomato gravy',
      },
      {
        id: 'fd-7',
        title: 'Dum Biryani',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/%22Hyderabadi_Dum_Biryani%22.jpg/440px-%22Hyderabadi_Dum_Biryani%22.jpg',
        category: 'Indian',
        subtitle: 'Aromatic saffron basmati rice',
      },
      {
        id: 'fd-8',
        title: 'Butter Croissant',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flaky_pastry_-_Croissant.jpg/440px-Flaky_pastry_-_Croissant.jpg',
        category: 'Bakery',
        subtitle: 'Golden flaky layers',
      },
      {
        id: 'fd-9',
        title: 'Italian Gelato',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Mmmm..._gelato%21_%283629007481%29.jpg/440px-Mmmm..._gelato%21_%283629007481%29.jpg',
        category: 'Dessert',
        subtitle: 'Pistachio & dark chocolate',
      },
      {
        id: 'fd-10',
        title: 'Smoked Texas BBQ Ribs',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Smoked_Baby_Back_Ribs.jpg/440px-Smoked_Baby_Back_Ribs.jpg',
        category: 'BBQ',
        subtitle: 'Fall-off-the-bone tender',
      },
    ],
    containers: {
      'tier-s': ['fd-1', 'fd-2'],
      'tier-a': ['fd-3', 'fd-5'],
      'tier-b': ['fd-4'],
      'tier-c': [],
      'tier-d': [],
      POOL: ['fd-6', 'fd-7', 'fd-8', 'fd-9', 'fd-10'],
    },
  },
  {
    id: 'blank',
    name: 'Blank Custom Template',
    description: 'Start from scratch with your own custom tiers and items',
    icon: '✨',
    category: 'Custom',
    title: 'My Custom Tier List',
    subtitle: 'Create, customize, and rank anything you want',
    author: 'Live Streamer',
    tiers: DEFAULT_TIERS,
    items: [],
    containers: {
      'tier-s': [],
      'tier-a': [],
      'tier-b': [],
      'tier-c': [],
      'tier-d': [],
      'tier-f': [],
      POOL: [],
    },
  },
]